### ISSUE TITLE
Additional values in building-coordinates.json to apply filters

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/transform-bvl-csv-to-json-files#1]
@k00ni 

To apply our filters to the result buildings we need some more values in the `building-coordinates.json`

Each entry needs additional:

- title
- category
- availability of elevator, toilet, parking, additional help
- accessibility of entry, elevator, toilet, parking

Hopefully the result file (may rename to `buildings-overview.json`) doesn't gets too big. But I dont's see any alternative way.

**Comment by k00ni** [comment]
I can do that. Is it OK to provide this in January 2017?

**Comment by simeonackermann** [comment]
Thats Ok!
I can start with just some example entries.

**Comment by k00ni** [comment]
Adapted the file and added required fields. Please check if it fits now.

Example entry:

```
{
	"title": "Alter Johannisfriedhof",
	"longitude": 12.3953192,
	"latitude": 51.3321392,
	"entrance-suit-f-wheelchair": 1,
	"lift-suit-f-wheelchair": 0,
	"lift-avail": 0,
	"toilet-suit-f-wheelchair": 0,
	"parking-avail": 1,
	"parking-f-disabled-avail": 0,
	"help-for-hearing-imp": 0,
	"help-for-blind": 0,
	"general-help": 0
}
```

**Comment by simeonackermann** [comment]
We also need the **category** for each entry.

And there is one not yet covered case: if the entrance is **partly** wheelchair accessible  (`eingangsbereich_rollstuhlgerecht: teilweise`, e.g. [11-polnisches-institut-markt-10-04109-leipzig)](https://github.com/AKSW/transform-bvl-csv-to-json-files/blob/master/result/buildings/11-polnisches-institut-markt-10-04109-leipzig.json).

Solution proposals:

- add one more line per entry `entrance-partly-suit-f-wheelchair`, which is also true if the entrance is fully wheelchair accessible. 
- or change value of `lift-suit-f-wheelchair` to string-value like "yes|no|partly".

**Comment by k00ni** [comment]
I will add category field soon.

> And there is one not yet covered case: if the entrance is partly wheelchair accessible 

I forgot to tell you. The value ranges from 0 to 2, where 0 means not suitable, 1 means partly and 2 means fully.

**Comment by k00ni** [comment]
Added category to coordinates file. Anything still missing?

**Comment by simeonackermann** [comment]
Seems fine for the moment.

Do you think the first empty entry (`"ID":{"category":"Kategorie","title":"Titel","longitude":0,"latitude":0,"entrance-suit-f-wheelchair":0,"lift-suit-f-wheelchair":0,"lift-avail":0,"toilet-suit-f-wheelchair":0,"parking-avail":0,"parking-f-disabled-avail":0,"help-for-hearing-imp":0,"help-for-blind":0,"general-help":0`) is important?
Otherwise it can removed.

**Comment by simeonackermann** [comment]
`entrance-suit-f-wheelchair` is not correct. Its always 0 or 1 but never 2, as aspected for partly, e.g. in [1-botanischer-garten-der-universitaet-leipzig-linn%C3%A9str.-1-04103-leipzig.json](https://github.com/AKSW/transform-bvl-csv-to-json-files/blob/master/result/buildings/1-botanischer-garten-der-universitaet-leipzig-linn%C3%A9str.-1-04103-leipzig.json)

**Comment by simeonackermann** [comment]
Require field for availability of toilet `toilet-avail`

**Comment by k00ni** [comment]
Hi, here are my latest changes:

* i removed `ß` from the keys, so please adapt these in the building files
* added field `toilet-avail`
* fixed field `entrance-suit-f-wheelchair` (possible values are now 0, 1 and 2, whereas 2 means fully accessible by wheelchairs)

**Comment by k00ni** [comment]
I think we are done here.
