### ISSUE TITLE
If elevator is wheelchair accessible elevator is also available

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/transform-bvl-csv-to-json-files#2]
In some datasets (e.g. https://github.com/AKSW/transform-bvl-csv-to-json-files/blob/master/result/buildings/44-stadtgeschichtliches-museum-leipzig-neubau-boettchergaesschen-3-04109-leipzig.json) the value for `personenaufzug_rollstuhlgerecht` is `ja`, but `personenaufzug_vorhanden` is `nein`. 

In my view this is not possible. If the elevator is wheelchair accessible its also available.

**Comment by k00ni** [comment]
That's a general error and must be discussed with the Behindertenverband Leipzig. I guess my current transformation program does not handle this well. Is on my TODO list. 

Does it affects you negatively?

**Comment by k00ni** [comment]
I fixed that in the latest commit. From now on, if the elevator is marked as suitable for wheelchairs, it is also `available`.
