### ISSUE TITLE
latitude langitude as float

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/transform-bvl-csv-to-json-files#3]
The values for latitude and longitude in the result files could saved as float value.

**Comment by k00ni** [comment]
Current form is:

```
{"longitude":12.473399,"latitude":51.3456877}
```

What do you mean with "float value" ? Isn't that already in float?

**Comment by simeonackermann** [comment]
In the result file if a building the values are strings. 

Am 21. Dezember 2016 11:59:05 MEZ, schrieb Konrad Abicht <notifications@github.com>:
>Current form is:
>
>```
>{"longitude":12.473399,"latitude":51.3456877}
>```
>
>What do you mean with "float value" ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AKSW/transform-bvl-csv-to-json-files/issues/3#issuecomment-268494983

-- 
Diese Nachricht wurde von meinem CyanogenMod Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by k00ni** [comment]
Fixed in the next commit.

**Comment by k00ni** [comment]
Ok now?

**Comment by simeonackermann** [comment]
yep
