### ISSUE TITLE
Places with latitude/longitude is zero

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/transform-bvl-csv-to-json-files#4]
There are 23 places with latitude and longitude is zero, e.g. [3-freizeitpark-loessnig-am-silbersee-04279-leipzig](https://github.com/AKSW/transform-bvl-csv-to-json-files/blob/master/result/buildings/3-freizeitpark-loessnig-am-silbersee-04279-leipzig.json) (also in building-coordinates.json). I guess this is not a mistake of the transformation, but of the source bvl data?

However, these places will never appear on the map.

**Comment by k00ni** [comment]
My bad, i guess the algorithm to transform addresses to long/lat does not work well here. Please ignore that for now, i will do some research on that.
